### ISSUE TITLE
Direct link redirects to previous locale.

### ISSUE THREAD

**Issue by RollingTL** [positivecrash/gridsome-plugin-translateit#1]
gridsome.config.js
```
const yaml = require("js-yaml");
const fs = require("fs");

module.exports = {
  siteName: "site",
  plugins: [
    {
      use: "gridsome-plugin-translateit",
      options: {
        locales: ["ru", "en"],
        defaultLocale: "ru",
        slugifyDefaultLocale: false, 
        translations: yaml.load(
          fs.readFileSync("./src/data/locales/translations.yaml", "utf8")
        ),
        exclude: ["/404/", "/sitemap.xml/"], // this is default value
        routes: yaml.load(
          fs.readFileSync("./src/data/locales/routes.yaml", "utf8")
        ),
      },
    },
  ],
};
```
Looks like site remembers your last locale. If your last locale was en and your rout was **site.loc/en/about/** and even if you close browser page, and open new one and paste link **site.loc/about/** site will again redirect to initial local route **site.loc/en/about/**.

In case you will try to have links instead of selector to change locale it will not work also.

That behavior is not good for ceo, and is not what url is supposed to be.  

Is it possible to make behavior change to detect and change locale when route initially detected?

**Comment by RollingTL** [comment]
Now locale is stored in Local Storage. And when entering site local is taken fro Local Storage. But it would be better to take it from the route. Maybe its better not to use Local Storage. All info is in the route.

**Comment by RollingTL** [comment]
I will make pull request removing Local Storage initial check and on change writing.

**Comment by positivecrash** [comment]
Hi, @RollingTL thanks for your contribution!
I watched your PR and agree with suggested by you prior routing from url. Can you please make PR from your fork to my repo, so I could merge it?

**Comment by positivecrash** [comment]
I have updated package, see 1.0.8 version. Thanks a lot for your contribution!
